dist: xenial
language: generic
install:
- pip install --user pygments restructuredtext-lint
script:
- shellcheck hg-*
- ./hg-clone-to-bundle http://blitz.works/noauthsftp
- file noauthsftp.hg
- restructuredtext-lint --encoding=UTF-8 README

# vim:ts=2 sts=2 sw=2 et
