#!/bin/sh

# Copyright © 2016-2018 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

for dir in $(find -xdev -type d -name '.hg')
do
    dir="${dir%/.hg}"
    dir="${dir#./}"
    printf '[\033[1m%s\033[0m]\n' "$dir"
    hg --cwd "$dir" "$@"
done

# vim:ts=4 sts=4 sw=4 et
