#!/bin/sh

# Copyright © 2016-2018 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

set -u
findopts=
while getopts 'L' opt
do
    case "$opt" in
        L) findopts='-L';;
        *) exit 1;;
    esac
done
shift $((OPTIND - 1))
template=$(hg --cwd / config forall.template) || template='==> %s <=='
find $findopts . -xdev -type d -name '.hg' -print -prune |
while read -r dir
do
    dir="${dir%/.hg}"
    dir="${dir#./}"
    # shellcheck disable=SC2059
    printf "$template"'\n' "$dir"
    hg --cwd "$dir" "$@"
    printf '\n'
done

# vim:ts=4 sts=4 sw=4 et
