#!/bin/sh

# Copyright © 2016-2018 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

find -xdev -type d -name '.hg' -print -prune |
while read -r dir
do
    dir="${dir%/.hg}"
    dir="${dir#./}"
    printf '[\033[1m%s\033[0m]\n' "$dir"
    hg --cwd "$dir" "$@"
    printf '\n'
done

# vim:ts=4 sts=4 sw=4 et
