#!/bin/sh

for file in "$@"
do
    fileo=$(mktemp -t $(basename -- "$file").XXXXXXXX) || exit 1
    hg cat -- "$file" > "$fileo"
    chmod a-w "$fileo"
    if cmp -s -- "$file" "$fileo"
    then
        :
    else
        vim -d "$file" "$fileo"
    fi
    rm -f "$fileo"
done

# vim:ts=4 sts=4 sw=4 et
