#!/bin/sh

# Copyright © 2008-2018 Jakub Wilk <jwilk@jwilk.net>
# SPDX-License-Identifier: MIT

for file in "$@"
do
    fileo=$(mktemp -t "${file##*/}.XXXXXXXX") || exit 1
    hg cat -- "$file" > "$fileo"
    chmod a-w "$fileo"
    if cmp -s -- "$file" "$fileo"
    then
        :
    else
        vim -d "$file" "$fileo"
    fi
    rm -f "$fileo"
done

# vim:ts=4 sts=4 sw=4 et
